server:
  port: 8000
spring:
  application:
    name: msa1
  session:
    store-type: redis
  redis:
    host: alcava00.synology.me
    port: 16379

eureka:
  instance:
#      instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    region: default
    fetch-registry: true
    enabled: true
    registry-fetch-interval-seconds: 4
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9000/eureka/

hystrix.command.default.circuitBreaker.enabled: true
hystrix.command.default.execution.timeout.enabled: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 1000
hystrix.command.default.circuitBreaker.errorThresholdPercentage: 10
hystrix.command.default.circuitBreaker.sleepWindowInMilliseconds: 5000
hystrix.collapser.default.maxRequestsInBatch: 5
hystrix.command.default.metrics.rollingStats.timeInMilliseconds: 5000
hystrix.threadpool.default.coreSize: 30
#hystrix.command.default.circuitBreaker.forceOpen: true
#hystrix.command.default.circuitBreaker.forceClosed: true
logging:
  level:
    com.netflix.hystrix: debug
    org.springframework.session: DEBUG
management.security.enabled: false