server:
  port: 8000
spring:
  application:
    name: msa1
  session:
    store-type: redis


hystrix.command.default.circuitBreaker.enabled: true
hystrix.command.default.execution.timeout.enabled: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 1000
hystrix.command.default.circuitBreaker.errorThresholdPercentage: 10
hystrix.command.default.circuitBreaker.sleepWindowInMilliseconds: 5
#hystrix.command.default.circuitBreaker.forceOpen: true
#hystrix.command.default.circuitBreaker.forceClosed: true
logging:
  level: debug
#    com.netflix.hystrix: debug
