server:
  port: 8001

spring:
  application:
    name: bff
  session:
    store-type: redis
    redis:
      flush-mode: immediate
  redis:
    host: alcava00.synology.me
    port: 16379

eureka:
  instance:
  #      instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    region: default
    fetch-registry: true
    enabled: true
    registry-fetch-interval-seconds: 4
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9000/eureka/
    eureka-service-url-poll-interval-seconds: 3000

logging:
  level:
    com.example: DEBUG
    org.springframework.session: DEBUG